version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /data/create.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./ddl:/data
    environment:
      - MYSQL_DATABASE=dockerdb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - docker-net

  node:
    build:
      context: node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: bash -c "npm i && node /usr/src/app/index.js"
    tty: true
    volumes:
      - ./node:/usr/src/app
    networks:
      - docker-net
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - docker-net
    ports:
      - "8080:80"
    depends_on:
      - node

networks:
  docker-net:
    driver: "bridge"
